### ISSUE TITLE
Cannot access CC website via HTTPS

### ISSUE THREAD

**Issue by lofidevops** [ContributorCovenant/community_covenant#7]
**Steps to reproduce:**

* Visit https://community-covenant.net

**What should happen:**

* Website is visible

**What happens instead:**

* Security warning (certificate from github.io)

**Comment by CoralineAda** [comment]
Thanks! Migrating to netlify now, this should be resolved today.

**Comment by CoralineAda** [comment]
Looks like it's working now, thanks for the report!
